const mongoose = require('mongoose');

const gameSchema = new mongoose.Schema({
    id: Number,
    name: String,
    price: { type: Number, default: 0 },
    discount: String,
    stroke: Number,// 0 = Free
    available: String, 
    image: String, // URL to cover image
    genre: String,
    link: String,
    cardType: String,
    type: String,
    color: String,
    button: String,
    header: String,
    backgroundColor: String,
    free: String,
    texth3: String,
    textp: String,
    text: String,
    firstButton: String,
    secondButton: String,
    video: String,
    firstImage: String, 
    secondImage: String, 
    thirdImage: String,
    fourthImage: String, 
    productHeader: String, 
    btn1: String, 
    btn2: String, 
    btn3: String, 
    btn4: String, 
    aboutProductHeader: String, 
    aboutProductNote: String, 
    productLogo: String, 
    arcLogo: String, 
    productPlus: String, 
    productUser: String, 
    productBaseButton: String,  
    productBasegameText: String, 
    developer: String, 
    publisher: String, 
    releaseDate: String, 
    platformImage: String, 
    platformName: String, 
    osVersion: String, 
    cpu: String, 
    memory: String, 
    gpu: String, 
    storage: String, 
    loginAccount: String, 
    languagesSupported: String, 
    language_supported: String, 
    flaming_copyright: String,
});

module.exports = mongoose.model('Game', gameSchema);